### PR TITLE
Add legacy ion

### PR DESCRIPTION
**Pull request by etienne-lms**
This P-R implements OP-TEE ION changes for SDP support over the 6 current legacy patches in the Linux kernel, rebased on kernel v5.1:
* `staging/ion: add Allwinner ION "secure" heap`
* `ion: "unmapped" heap for secure data path` built from previous "secure heap" including dummy unammped heap create from kernel configuration.
* 4 changes found in the legacy OP-TEE kernel patch series fixing in ION unmapped support.

### CODE REVIEW

**Comment by etienne-lms** [comment]
This change gives the same source state as #1, with ION change commits aggregated at patch series top and #1 change squashed into `ion: "unmapped" heap for secure data path` commit as version rebase fixup.

**Comment by jforissier** [comment]
Thanks @etienne-lms, I can confirm this works fine on my HiKey960 (including the SDP tests [1]).

`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey960, SDP)`

@jenswi-linaro @jbech-linaro any concern with using this as our new optee branch in https://github.com/linaro-swg/linux?

[1] Tested with https://github.com/OP-TEE/build/pull/368.

**Comment by jockebech** [comment]
> @jenswi-linaro @jbech-linaro any concern with using this as our new optee branch in https://github.com/linaro-swg/linux?

Nope, I'm fine with this as it is here, thanks!

**Comment by etienne-lms** [comment]
I've added Tested-by tags for SDP on last commit.

**Comment by jenswikl** [comment]
Fine with me too!

**Comment by jforissier** [comment]
Excellent, thank you all, I'll update the optee branch shortly.

Edit: https://github.com/linaro-swg/linux branch optee updated, previous tip saved as tag `optee-v5.0-20190513`.

**Comment by jforissier** [comment]
Closing since the patches are now in the official linaro-swg optee branch.

**Pull request closed without merging**
